config/routes.rb
Rails.application.routes.draw do
  
  resources :departments do
    resources :employees
  end 

  devise_for :companies
  root to: 'departments#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :departments 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/department.rb
class Department < ApplicationRecord
    belongs_to :company
    has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_company!

  # GET /departments
  # GET /departments.json
  def index
    @departments = current_company.departments
    @department = Department.new
    @employees = Employee.all

  end

  # GET /departments/1
  # GET /departments/1.json
  def show 
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params) 
    @department.company = current_company

    respond_to do |format|
    
      if @department.save
        format.html { redirect_to departments_path, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department}
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to departments_path, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_company!

  # GET /employees
  # GET /employees.json
  def index
    @department = Department.find(params[:department_id])
    @employee = Employee.new
    @employees = @department.employees
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
    @department = Department.find(params[:department_id])
    @employees = @department.employees
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)
    @employee.department = Department.find(params[:department_id])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to department_employees_path, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to department_employees_path, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to department_employees_path, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :lastname, :ci, :movil, :email, :bank_name, :bank_type, :bank_account, :phone1, :phone2)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/departments/_form.html.haml
= form_for @department do |f|
  - if @department.errors.any?
    #error_explanation
      %h2= "#{pluralize(@department.errors.count, "error")} prohibited this department from being saved:"
      %ul
        - @department.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name  
  .actions
    = f.submit 'Save'

app/views/departments/edit.html.haml
%h1 Editing department

= render 'form'

= link_to 'Show', @department
\|
= link_to 'Back', departments_path

app/views/departments/index.html.haml
.container
  .row.p-2
    .col-9
      barra de busqueda
    .col-1
      submit
    .col-2.justify-content-center
      = link_to "Cerrar sesión", destroy_company_session_path, method: :delete
  .row.justify-content-center
    .col-12
      %p#notice= notice
    .col-7
      -if @departments.empty?
        
        %h1 no hay departamentos
      -else
        %table.table.border
          %thead
            %tr
              %th Nombre del departamento
              %th Cantidad de empleados
              %th Acciones

          %tbody
            - @departments.each do |department|
              %tr
                %td= department.name
                %td
                  =@employees.where(:department_id => department.id).length
                %td
                  = link_to 'Add', department_employees_path(:department_id => department.id)
                  = link_to 'Edit', edit_department_path(department)
                  = link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' }
    .col-5
      .border
        = render 'form'

    -# %br
    -# = link_to 'New Department', new_department_path

app/views/departments/new.html.haml
%h1 New department

= render 'form'

= link_to 'Back', departments_path

app/views/departments/show.html.haml
%p #notice= notice

%p
  %b Name:
  = @department.name

= link_to 'Edit', edit_department_path(@department)
\|
= link_to 'Back', departments_path

app/views/employees/_form.html.haml
= form_for [@department, @employee] do |f|
  - if @employee.errors.any?
    #error_explanation
      %h2= "#{pluralize(@employee.errors.count, "error")} prohibited this employee from being saved:"
      %ul
        - @employee.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :lastname
    = f.text_field :lastname
  .field
    = f.label :ci
    = f.number_field :ci
  .field
    = f.label :movil
    = f.number_field :movil
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :bank_name
    = f.text_field :bank_name
  .field
    = f.label :bank_type
    = f.number_field :bank_type
  .field
    = f.label :bank_account
    = f.number_field :bank_account
  .field
    = f.label :phone1
    = f.number_field :phone1
  .field
    = f.label :phone2
    = f.number_field :phone2
  .actions
    = f.submit 'Save'

app/views/employees/edit.html.haml
%h1 Editing employee

= render 'form'

= link_to 'Show', [@department, @employee]
\|
= link_to 'Back', department_employees_path

app/views/employees/index.html.haml
.container
  .row.p-2
    .col-9
      barra de busqueda
    .col-1
      submit
    .col-2.justify-content-center
      = link_to "Cerrar sesión", destroy_company_session_path, method: :delete
  .row.justify-content-center
    .col-12
      %p#notice= notice
    .col-7
      .d-inline
        .div
          =link_to departments_path do
            %i.fas.fa-chevron-left.fa-2x 
          Empleados de
          = @department.name
      -if @employees.empty?
        
        %h1 no hay empleados
      -else
        %table.table.border
          %thead
            %tr
              %th Cedula
              %th  Nombre
              %th  Celular
              %th  Acciones  
          %tbody
            - @employees.each do |employee|
              %tr
                %td= employee.ci
                %td 
                  = employee.name
                  = employee.lastname 
                %td= employee.movil
              
                
                %td.text-center
                  
                  = link_to edit_department_employee_path(@department, employee) do
                    %i.fas.fa-pencil-alt
                  = link_to [@department, employee], method: :delete, data: { confirm: 'Are you sure?' } do
                    %i.fas.fa-trash.text-danger

    .col-5
      .border.p-4
        = render 'form'

app/views/employees/new.html.haml
%h1 New employee

= render 'form'

= link_to 'Back', departments_path

app/views/employees/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @employee.name
%p
  %b Lastname:
  = @employee.lastname
%p
  %b Ci:
  = @employee.ci
%p
  %b Movil:
  = @employee.movil
%p
  %b Email:
  = @employee.email
%p
  %b Bank name:
  = @employee.bank_name
%p
  %b Bank type:
  = @employee.bank_type
%p
  %b Bank account:
  = @employee.bank_account
%p
  %b Phone1:
  = @employee.phone1
%p
  %b Phone2:
  = @employee.phone2

= link_to 'Edit', edit_employee_path(@employee)
\|
= link_to 'Back', employees_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EmployeesCard
    %script{:defer => "defer", :src => "https://use.fontawesome.com/releases/v5.0.6/js/all.js"}   
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield